# -*- coding: utf-8 -*-
"""py1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSO2Ne8jeUQY-XIBU7yura0Ie024Fahw
"""

class Fetcher :

  def __init__(self):
    import requests as r
    self.__students=r.get("https://cdn.ituring.ir/ex/users.json").json()
    return None

  def nerds (self):
     STUDENTS=set()
     for students in self.__students :
       if students["score"]>=18.5:
         A=students["name"] + "-" + students["last_name"]
         STUDENTS.add(A)
         continue
     return STUDENTS

  def sultans (self):
     TOP_STUDENTS=[]
     maximum_score = 0
     for students in self.__students :
      if students["score"]>=maximum_score :
       maximum_score=students["score"]
       continue
     for students in self.__students :
      if students["score"]==maximum_score :
        B=students["name"] + "-" + students["last_name"]
        TOP_STUDENTS.append(B)
        continue
     return tuple(TOP_STUDENTS)

  def mean (self):
    population=len(self.__students)
    sum=0
    for students in self.__students :
      sum=sum+students["score"]
      continue
    return sum/population

  def get_students (self):
    stu_l=[]
    for students in self.__students :
      C={"name" : students["name"],"last_name" : students["last_name"],"height" : students["height"],"weight" : students["weight"],"score" : students["score"],"savings" : students["savings"],"salary" : students["salary"]}
      stu_l.append(C)
      continue
    return stu_l

F = Fetcher()
print(F.nerds())
print(F.sultans())
print(F.mean())
print(F.get_students())
